services:
  - type: web
    name: spectra-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "10000"
